In [1]:
import numpy as np

In [2]:
# cholesky decomposition by rows algorithm implementation
def cholesky_decomp(A):
    L = np.zeros_like(A)
    n = len(L)
    for i in range(n):
        for j in range(i+1):#algo for j=1~i-1, but python starts with 0 so it's till i, but range does not include i+1
            if i==j:
                L[i,i] = np.sqrt(A[i,i]-np.sum(np.square(L[i,:i]))) #array[:i] means elements till i-1
            else:
                L[i,j] = (A[i,j] - np.sum(L[i,:j]*L[j,:j]))/L[j,j]
    return L

In [3]:
# test that cholesky_decomp() is correct
A = np.random.randn(10,10)
A = A.dot(A.T) # now A is positive definite

In [4]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [5]:
is_pos_def(A)

True

In [6]:
my_cholesky_decomposition = cholesky_decomp(A)
python_cholesky_decomposition = np.linalg.cholesky(A)
np.allclose(my_cholesky_decomposition, python_cholesky_decomposition)

True

In [7]:
# algorithms for solving the system Ax =b
# using the Cholesky decomposition algorithm

def solve_cholesky_forwards(A, b):
    n = len(b)
    x = [b[0] / A[0, 0]]
    for i in range(1,n):
        x.append((b[i] - A[i, i - 1] * x[i - 1]) / A[i, i])
    return np.array(x)

def solve_cholesky_backwards(A, b):
    n = len(b)
    x = [b[n - 1] / A[n - 1, n - 1]] # that's the last element, so will have to reverse x in the end
    count = 0
    for i in range(n-2,-1,-1):
        count += 1
        x.append((b[i] - A[i, i + 1] * x[count - 1]) / A[i, i])
    return np.array(x[::-1])

def solve_cholesky(A,b):
    L = cholesky_decomp(A)
    y = solve_cholesky_forwards(L,b)
    x = solve_cholesky_backwards(L.T,y)
    return x

In [8]:
# Test that solving algorithms are correct
M = np.array([[2.,-1.,0.],
              [-1.,2.,-1.],
              [0.,-1.,2.]])
b = np.array([2.,1.,0.])
print(is_pos_def(M))
np_solution = np.linalg.solve(M,b)
my_solution = solve_cholesky(M, b)
print(np.allclose(my_solution, np_solution))
print(my_solution)
print(np_solution)

True
True
[2. 2. 1.]
[2. 2. 1.]


In [9]:
# Solving Ax=b problem
# where A is 500x500 tridiagonal, positive definite
# and:
# di = 1000 + i 1<=i<=500
# ei = 1 + i    2<=i<=500
# bi = 1 + i    1<=i<=500

A = np.zeros((500,500))

d = np.float64(np.arange(1001,1502))
e = np.float64(np.arange(3,502))

n = len(A)
A[0,0] = d[0]
for i in range(1,n):
    A[i,i] = d[i] 
    A[i,i-1] = e[i-1]
    A[i-1,i] = e[i-1]
print(A)

b = np.arange(2,502)
print(is_pos_def(A))

[[1001.    3.    0. ...    0.    0.    0.]
 [   3. 1002.    4. ...    0.    0.    0.]
 [   0.    4. 1003. ...    0.    0.    0.]
 ...
 [   0.    0.    0. ... 1498.  500.    0.]
 [   0.    0.    0. ...  500. 1499.  501.]
 [   0.    0.    0. ...    0.  501. 1500.]]
True


In [10]:
# Cholesky decomposition of matrix A
my_chol = cholesky_decomp(A)
np_chol = np.linalg.cholesky(A)
print(my_chol)
print(np_chol)
np.allclose(my_chol, np_chol)

[[31.63858404  0.          0.         ...  0.          0.
   0.        ]
 [ 0.09482093 31.65424156  0.         ...  0.          0.
   0.        ]
 [ 0.          0.12636537 31.66992314 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ... 36.15967674  0.
   0.        ]
 [ 0.          0.          0.         ... 13.82755724 36.16349901
   0.        ]
 [ 0.          0.          0.         ...  0.         13.85374794
  36.16730109]]
[[31.63858404  0.          0.         ...  0.          0.
   0.        ]
 [ 0.09482093 31.65424156  0.         ...  0.          0.
   0.        ]
 [ 0.          0.12636537 31.66992314 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ... 36.15967674  0.
   0.        ]
 [ 0.          0.          0.         ... 13.82755724 36.16349901
   0.        ]
 [ 0.          0.          0.         ...  0.         13.85374794
  36.16730109]]


True

In [11]:
# solve Ax = b using my algorithm and numpy's to compare
my_solution = solve_cholesky(A,b)
np_solution = np.linalg.solve(A,b)

In [12]:
my_solution

array([0.00198909, 0.00297228, 0.00395163, 0.00492518, 0.005893  ,
       0.00685513, 0.00781162, 0.00876252, 0.00970788, 0.01064775,
       0.01158218, 0.01251121, 0.01343489, 0.01435327, 0.01526639,
       0.0161743 , 0.01707703, 0.01797465, 0.01886718, 0.01975468,
       0.02063718, 0.02151472, 0.02238736, 0.02325512, 0.02411806,
       0.0249762 , 0.0258296 , 0.02667828, 0.02752229, 0.02836167,
       0.02919646, 0.03002668, 0.03085239, 0.03167361, 0.03249038,
       0.03330275, 0.03411074, 0.03491439, 0.03571373, 0.0365088 ,
       0.03729964, 0.03808627, 0.03886873, 0.03964706, 0.04042128,
       0.04119143, 0.04195754, 0.04271965, 0.04347778, 0.04423196,
       0.04498223, 0.04572861, 0.04647114, 0.04720985, 0.04794476,
       0.04867591, 0.04940331, 0.05012702, 0.05084704, 0.05156341,
       0.05227615, 0.0529853 , 0.05369088, 0.05439291, 0.05509143,
       0.05578646, 0.05647803, 0.05716616, 0.05785087, 0.0585322 ,
       0.05921017, 0.0598848 , 0.06055612, 0.06122415, 0.06188

In [13]:
np_solution

array([0.00198909, 0.00297228, 0.00395163, 0.00492518, 0.005893  ,
       0.00685513, 0.00781162, 0.00876252, 0.00970788, 0.01064775,
       0.01158218, 0.01251121, 0.01343489, 0.01435327, 0.01526639,
       0.0161743 , 0.01707703, 0.01797465, 0.01886718, 0.01975468,
       0.02063718, 0.02151472, 0.02238736, 0.02325512, 0.02411806,
       0.0249762 , 0.0258296 , 0.02667828, 0.02752229, 0.02836167,
       0.02919646, 0.03002668, 0.03085239, 0.03167361, 0.03249038,
       0.03330275, 0.03411074, 0.03491439, 0.03571373, 0.0365088 ,
       0.03729964, 0.03808627, 0.03886873, 0.03964706, 0.04042128,
       0.04119143, 0.04195754, 0.04271965, 0.04347778, 0.04423196,
       0.04498223, 0.04572861, 0.04647114, 0.04720985, 0.04794476,
       0.04867591, 0.04940331, 0.05012702, 0.05084704, 0.05156341,
       0.05227615, 0.0529853 , 0.05369088, 0.05439291, 0.05509143,
       0.05578646, 0.05647803, 0.05716616, 0.05785087, 0.0585322 ,
       0.05921017, 0.0598848 , 0.06055612, 0.06122415, 0.06188

In [14]:
# check if my solution and numpy solution are the same
np.allclose(my_solution,np_solution)

True